// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lygyeesqdenbauimkrjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5Z3llZXNxZGVuYmF1aW1rcmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMDg4MjQsImV4cCI6MjA4NTY4NDgyNH0.p6E_tk81qo-j2-9RTXMba4UqiObS5Esvx7TJBTYuD1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});